# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-inventory-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.inventoryService.replicaCount }}
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.inventoryService.securityContext.podLevel.runAsNonRoot }}
        runAsUser: {{ .Values.inventoryService.securityContext.podLevel.runAsUser }}
        runAsGroup: {{ .Values.inventoryService.securityContext.podLevel.runAsGroup }}
        fsGroup: {{ .Values.inventoryService.securityContext.podLevel.fsGroup }}
        seccompProfile:
          type: {{ .Values.inventoryService.securityContext.podLevel.seccompProfile.type }}
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z mongo-inventory.microservices.svc.cluster.local 27017; do echo waiting for mongo-inventory; sleep 10; done']
          securityContext:
            allowPrivilegeEscalation: {{ .Values.inventoryService.securityContext.containerLevel.allowPrivilegeEscalation }}
            capabilities:
              drop: {{- toYaml .Values.inventoryService.securityContext.containerLevel.capabilities.drop | nindent 16 }}
            readOnlyRootFilesystem: {{ .Values.inventoryService.securityContext.containerLevel.readOnlyRootFilesystem }}
      containers:
        - name: inventory-service
          image: "{{ .Values.inventoryService.image.repository }}:{{ .Values.inventoryService.image.tag }}"
          ports:
            - containerPort: {{ .Values.inventoryService.service.port }}
          env:
            - name: MONGO_URI
              value: {{ .Values.inventoryService.mongo.uri }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.inventoryService.securityContext.containerLevel.allowPrivilegeEscalation }}
            capabilities:
              drop: {{- toYaml .Values.inventoryService.securityContext.containerLevel.capabilities.drop | nindent 16 }}
            readOnlyRootFilesystem: {{ .Values.inventoryService.securityContext.containerLevel.readOnlyRootFilesystem }}