# templates/mongo-inventory-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo-inventory
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.mongoInventory.replicas }}
  selector:
    matchLabels:
      app: mongo-inventory
  template:
    metadata:
      labels:
        app: mongo-inventory
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.mongoInventory.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.mongoInventory.securityContext.runAsUser }}
        runAsGroup: {{ .Values.mongoInventory.securityContext.runAsGroup }}
        fsGroup: {{ .Values.mongoInventory.securityContext.fsGroup }}
      containers:
        - name: mongo-inventory
          image: "{{ .Values.mongoInventory.image.repository }}:{{ .Values.mongoInventory.image.tag }}"
          imagePullPolicy: {{ .Values.mongoInventory.image.pullPolicy }}
          env:
            - name: MONGO_INITDB_DATABASE
              value: inventory_db
          ports:
            - containerPort: {{ .Values.mongoInventory.ports.mongo }}
          volumeMounts:
            - name: mongo-inventory-storage
              mountPath: /data/db
          securityContext:
            allowPrivilegeEscalation: {{ .Values.mongoInventory.securityContext.allowPrivilegeEscalation }}
            capabilities:
              drop: {{ toJson .Values.mongoInventory.securityContext.capabilities.drop }}
      volumes:
        - name: mongo-inventory-storage
          persistentVolumeClaim:
            claimName: mongo-inventory-pvc