# templates/zookeeper-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zookeeper
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.zookeeper.replicas }}
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.zookeeper.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.zookeeper.securityContext.runAsUser }}
        runAsGroup: {{ .Values.zookeeper.securityContext.runAsGroup }}
        fsGroup: {{ .Values.zookeeper.securityContext.fsGroup }}
      containers:
        - name: zookeeper
          image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
          imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.zookeeper.ports.service }}
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "{{ .Values.zookeeper.allowAnonymousLogin }}"
          securityContext:
            allowPrivilegeEscalation: {{ .Values.zookeeper.securityContext.allowPrivilegeEscalation }}
            capabilities:
              drop: {{- toYaml .Values.zookeeper.securityContext.capabilities.drop | nindent 16 }}
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /bitnami/zookeeper
            - name: zookeeper-config
              mountPath: /opt/bitnami/zookeeper/conf
      volumes:
        - name: zookeeper-storage
          persistentVolumeClaim:
            claimName: zookeeper-pvc
        - name: zookeeper-config
          emptyDir: {}