apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: microservices
type: Opaque
data:
  POSTGRES_USER: bXl1c2Vy  # 'myuser' base64 encoded
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==  # 'mypassword' base64 encoded
  POSTGRES_DB: b3JkZXJzX2Ri  # 'orders_db' base64 encoded