apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Set the required storage size for ZooKeeper data
  storageClassName: standard  # Use the appropriate storage class (depends on your environment)