global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'kafka-brokers'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'kafka-streams'
    static_configs:
      - targets: ['kafka-streams:7071'] # Assuming you're exposing metrics on this port