{
 "title": "Kafka Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages Produced per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_topic_partition_current_offset{topic=\"order-created\"}[1m])",
     "legendFormat": "{{topic}} - Partition {{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"user-group\",topic=\"order-created\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Total Messages in Topic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"order-created\"}) - sum(kafka_topic_partition_oldest_offset{topic=\"order-created\"})"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_brokers", "legendFormat": "Brokers Online" }
   ]
  }
 ]
}