# templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-kafka-acl-setup
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app: kafka-acl-setup
    spec:
      containers:
        - name: kafka-acl-setup
          image: "{{ .Values.kafkaAclSetup.image.repository }}:{{ .Values.kafkaAclSetup.image.tag }}"
          imagePullPolicy: {{ .Values.kafkaAclSetup.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              sleep 30
              {{- range .Values.kafkaAclSetup.aclSetup.commands }}
              {{ . }}
              {{- end }}
          env:
            - name: KAFKA_OPTS
              value: "{{ .Values.kafkaAclSetup.kafka.jaasConfig.kafka_opts }}"
          volumeMounts:
            - name: kafka-secrets
              mountPath: /etc/kafka/secrets
              readOnly: true
      restartPolicy: {{ .Values.kafkaAclSetup.restartPolicy }}
      volumes:
        - name: kafka-secrets
          secret:
            secretName: {{ .Values.kafkaAclSetup.secrets.kafkaSecretName }}