# templates/kafka-configmap.yaml
{{- if .Values.kafka.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kafka.config.configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_LISTENERS: "SASL_SSL://0.0.0.0:9092"
  KAFKA_ADVERTISED_LISTENERS: "SASL_SSL://kafka:9092"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN"
  KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
  KAFKA_SECURITY_INTER_BROKER_PROTOCOL: "SASL_SSL"
  KAFKA_SSL_CLIENT_AUTH: "required"
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
  KAFKA_AUTHORIZER_CLASS_NAME: "kafka.security.authorizer.AclAuthorizer"
  KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
  ZOOKEEPER_SASL_ENABLED: "false"
  KAFKA_ZOOKEEPER_SET_ACL: "false"
  KAFKA_HEAP_OPTS: "-Xmx2g -Xms1g"
{{- end }}