# templates/prometheus-configmap.yaml
{{- if .Values.prometheus.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.config.configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kafka-exporter'
        static_configs:
          - targets: ['kafka-exporter:9308']
{{- end }}