# templates/network-policy.yaml
{{- if .Values.networkPolicies.allowInventoryService.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-graphql-to-inventory-service
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: inventory-service
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: graphql-gateway
      ports:
        - protocol: TCP
          port: {{ .Values.inventoryService.service.port }}
  policyTypes:
    - Ingress
{{- end }}