# templates/network-policy.yaml
{{- if .Values.networkPolicies.allowGraphQL.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-graphql-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: graphql-gateway
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: {{ .Values.graphqlGateway.service.port }}
  policyTypes:
    - Ingress
{{- end }}