# templates/mongo-users-network-policy.yaml
{{- if .Values.networkPolicies.allowMongoUsers.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mongo-users
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: mongo-users
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: users-service
  policyTypes:
    - Ingress
{{- end }}