# templates/postgres-network-policy.yaml
{{- if .Values.networkPolicies.allowPostgres.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postgres
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: postgres
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: orders-service
  policyTypes:
    - Ingress
{{- end }}