# templates/allow-kafka-to-zookeeper.yaml
{{- if .Values.networkPolicies.allowZookeeper.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kafka-to-zookeeper
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: zookeeper
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: kafka
  policyTypes:
    - Ingress
{{- end }}