# templates/mongo-inventory-network-policy.yaml
{{- if .Values.networkPolicies.allowMongoInventory.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mongo-inventory
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: mongo-inventory
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: inventory-service
  policyTypes:
    - Ingress
{{- end }}