# templates/allow-graphql-to-users-service.yaml
{{- if .Values.networkPolicies.allowUsersService.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-graphql-to-users-service
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: users-service
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: graphql-gateway
  policyTypes:
    - Ingress
{{- end }}