# templates/network-policy.yaml
{{- if .Values.networkPolicies.allowGrafana.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grafana-external
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: grafana
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: {{ .Values.grafana.service.port }}
  policyTypes:
    - Ingress
{{- end }}