# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-graphql-gateway
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.graphqlGateway.service.type }}
  ports:
    - port: {{ .Values.graphqlGateway.service.port }}
  selector:
    app: graphql-gateway