# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inventory-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.inventoryService.service.type }}
  ports:
    - port: {{ .Values.inventoryService.service.port }}
  selector:
    app: inventory-service