# templates/kafka-exporter-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-exporter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.kafkaExporter.ports.exporter }}
  selector:
    app: kafka-exporter