# templates/kafka-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.kafka.ports.kafka }}
  selector:
    app: kafka