# templates/orders-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-orders-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.ordersService.ports.service }}
  selector:
    app: orders-service