# templates/postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.postgres.ports.service }}
  selector:
    app: postgres