# templates/users-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.usersService.ports.service }}
  selector:
    app: users-service