apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-gateway
  template:
    metadata:
      labels:
        app: graphql-gateway
    spec:
      # Pod-level Security Context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000            # Non-root UID
        runAsGroup: 1000           # Non-root GID
        fsGroup: 2000              # File system group
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: graphql-gateway
          image: clementbonal/microservice-project_graphql:v3
          ports:
            - containerPort: 4000
          env:
            - name: USERS_SERVICE_URL
              value: http://users-service:3001
            - name: ORDERS_SERVICE_URL
              value: http://orders-service:3002
            - name: INVENTORY_SERVICE_URL
              value: http://inventory-service:3003
          # Container-level Security Context
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-gateway
  namespace: microservices
spec:
  type: LoadBalancer
  ports:
    - port: 4000
  selector:
    app: graphql-gateway