apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      # Pod-level Security Context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000            # Non-root UID
        runAsGroup: 1000           # Non-root GID
        fsGroup: 2000              # File system group
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z mongo-inventory.microservices.svc.cluster.local 27017; do echo waiting for mongo-inventory; sleep 10; done']
          # Container-level Security Context
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      containers:
        - name: inventory-service
          image: clementbonal/microservice-project_inventory-service:v2
          ports:
            - containerPort: 3003
          env:
            - name: MONGO_URI
              value: mongodb://mongo-inventory:27017/inventory_db
          # Container-level Security Context
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: microservices
spec:
  ports:
    - port: 3003
  selector:
    app: inventory-service