apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-acl-setup
  namespace: microservices
spec:
  template:
    metadata:
      labels:
        app: kafka-acl-setup
    spec:
      containers:
        - name: kafka-acl-setup
          image: wurstmeister/kafka:latest
          command:
            - /bin/bash
            - -c
            - |
              sleep 30
              kafka-topics.sh --create --if-not-exists --zookeeper zookeeper:2181 --topic order-created --partitions 3 --replication-factor 1
              kafka-acls.sh --authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:order-service --producer --topic order-created
              kafka-acls.sh --authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:user-service --consumer --topic order-created --group user-group
          envFrom:
            - configMapRef:
                name: kafka-config
            - secretRef:
                name: kafka-secrets
          volumeMounts:
            - name: kafka-secrets
              mountPath: /etc/kafka/secrets
              readOnly: true
      restartPolicy: OnFailure
      volumes:
        - name: kafka-secrets
          secret:
            secretName: kafka-secrets