apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      # Pod-level Security Context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000            # Non-root UID
        runAsGroup: 1000           # Non-root GID
        fsGroup: 2000              # File system group
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kafka-exporter
          image: danielqsj/kafka-exporter:latest
          args:
            - '--kafka.server=kafka:9092'
            - '--sasl.enabled'
            - '--sasl.username=kafka-exporter'
            - '--sasl.password=kafka-exporter-secret'
            - '--sasl.mechanism=PLAIN'
            - '--tls.enabled'
            - '--tls.ca-file=/etc/kafka/secrets/ca-cert.pem'
            - '--tls.cert-file=/etc/kafka/secrets/kafka-exporter-certificate.pem'
            - '--tls.key-file=/etc/kafka/secrets/kafka-exporter-key.pem'
            - '--tls.insecure-skip-tls-verify'
            - '--topic.filter=^order-created$$'
            - '--log.level=info'
          ports:
            - containerPort: 9308
          volumeMounts:
            - name: kafka-exporter-secrets
              mountPath: /etc/kafka/secrets
              readOnly: true
          # Container-level Security Context
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: kafka-exporter-secrets
          secret:
            secretName: kafka-exporter-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: microservices
spec:
  ports:
    - port: 9308
  selector:
    app: kafka-exporter