apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-acl-setup
  namespace: microservices
spec:
  template:
    metadata:
      labels:
        app: kafka-acl-setup
    spec:
      containers:
        - name: kafka-acl-setup
          image: wurstmeister/kafka:latest
          command:
            - /bin/bash
            - -c
            - |
              sleep 30
              kafka-acls.sh --authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:order-service --producer --topic order-created
              kafka-acls.sh --authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:user-service --consumer --topic order-created --group user-group
          env:
            - name: KAFKA_OPTS
              value: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"
          volumeMounts:
            - name: kafka-secrets
              mountPath: /etc/kafka/secrets
              readOnly: true
      restartPolicy: OnFailure
      volumes:
        - name: kafka-secrets
          secret:
            secretName: kafka-secrets