apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/data
            - name: kafka-secrets
              mountPath: /etc/kafka/secrets
              readOnly: true
          envFrom:
            - configMapRef:
                name: kafka-config
          env:
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_SSL_KEYSTORE_LOCATION
              value: "/etc/kafka/secrets/kafka.server.keystore.jks"
            - name: KAFKA_SSL_KEYSTORE_PASSWORD
              value: "kafka123"
            - name: KAFKA_SSL_KEY_PASSWORD
              value: "kafka123"
            - name: KAFKA_SSL_TRUSTSTORE_LOCATION
              value: "/etc/kafka/secrets/kafka.server.truststore.jks"
            - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
              value: "kafka123"
            - name: KAFKA_OPTS
              value: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pvc
        - name: kafka-secrets
          secret:
            secretName: kafka-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: microservices
spec:
  ports:
    - port: 9092
  selector:
    app: kafka
