apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-inventory
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-inventory
  template:
    metadata:
      labels:
        app: mongo-inventory
    spec:
      # Pod-level Security Context
      securityContext:
        runAsNonRoot: true
        runAsUser: 999            # Non-root UID
        runAsGroup: 999           # Non-root GID
        fsGroup: 999              # File system group
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mongo-inventory
          image: mongo:4.4
          env:
            - name: MONGO_INITDB_DATABASE
              value: inventory_db
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-inventory-storage
              mountPath: /data/db
          # Container-level Security Context
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            # Removed readOnlyRootFilesystem to allow writes to data directory
      volumes:
        - name: mongo-inventory-storage
          persistentVolumeClaim:
            claimName: mongo-inventory-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-inventory
  namespace: microservices
spec:
  ports:
    - port: 27017
  selector:
    app: mongo-inventory